spring:
  application:
    name: issp-eureka-server
server:
  port: 9701
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  security:
    enabled: false