spring:
  application:
    name: issp-eureka-server
  freemarker:
    suffix: .html
server:
  port: 9702
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
management:
  security:
    enabled: false